### ISSUE TITLE
Walking trail content

### ISSUE THREAD

**Issue by mantl002** [hiltaba/hiltaba.github.io#23]
Hiltaba offers a diverse group of walking trails with varying difficulties. Each walking trail exhibits its own unique fascinating scenery and panoramic views. The walking trails are shown below in the table.

It is important to note that the trails have different difficulties. 

> **All walkers should wear weather-protective clothing and strong footwear, carry an adequate supply of water (min. 2 litres per person), as well as an adequate supply of food. It is recommended that you do not walk alone. UHF Duplex ch6 can be used in an emergency. Limited Telstra mobile coverage may be available from higher points.** - Nature Foundation SA

Each trail has accompanying notes which can be accessed via the links below.

**Comment by JoshGore** [comment]
table added for walking trail comment. header image and content images/other still needed. I don't think the embedded mapillary viewer should stay there though.

**Comment by JoshGore** [comment]
nice work, pasted into site and popups. No images added.

**Comment by JoshGore** [comment]
Images inserted in 
https://github.com/hiltaba/hiltaba.github.io/commit/cdaa3dcc8dcc4c36f9f6b4d7f09d3dc60051f188 , https://github.com/hiltaba/hiltaba.github.io/commit/def116b6131505d38d164504256c7c5e819c5d8e , and https://github.com/hiltaba/hiltaba.github.io/commit/f49115ef9923d79319f5691e93a729fbf54949a5
